#!/bin/bash

source ./scripts/brew
source ./scripts/npm
source ./scripts/gem

# I do not want to write sudo everytime
sudo chown -R $USER /usr/local

# Install homebrew and its packages
echo "Installing brew..."
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update
brew_run

# Install GEM packages
gem_run

# NPM packages
npm_run

# Link everything
ln -fs "${PWD}/dotfiles/eslintrc" "${HOME}/.eslintrc"
ln -fs "${PWD}/dotfiles/gitconfig" "${HOME}/.gitconfig"
ln -fs "${PWD}/dotfiles/gitignore" "${HOME}/.gitignore"
ln -fs "${PWD}/dotfiles/stylintrc" "${HOME}/.stylintrc"
ln -fs "${PWD}/dotfiles/zshrc" "${HOME}/.zshrc"

# Composer
echo "Installing composer..."
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer

# Webponize
echo "Installing Webponize..."
curl -O https://1000ch.github.io/webponize/webponize.tar.gz
tar -zxvf webponize.tar.gz
rm webponize.tar.gz
mv WebPonize.app /Applications

echo "Installation completed!"
