#!/bin/bash

# Inspired by https://github.com/kewah/dotfiles/blob/master/scripts/brew

brew_tap() {
  if ! brew tap | grep "${@}" > /dev/null; then
    brew tap "${@}"
  fi
}

brew_install() {
  if ! $(brew list ${@} >/dev/null); then
    brew install ${@}
  fi
}

# Borrowed from https://github.com/MoOx/dotfiles/blob/master/bin/apps
cask_install() {
  if [ ! -d "$1" ] && [ ! -d "/Applications/$1/" ] && [ ! -d "/Applications/$1.app/" ] && [ ! -d "$HOME/Applications/$1.app/" ] && [ ! -d "$HOME/Applications/$1/" ]
  then
    brew cask install $2 --appdir="/Applications"
  fi
}

brew_run() {
  brew update
  brew upgrade

  echo "Homebrew:"
  echo "Installing packages..."

  local -a PACKAGES_NAME=(
    "git"
    "node"
    "pngquant"
    "wget"
    "zsh"
    "zsh-completions"
  )

  for index in ${!PACKAGES_NAME[*]}; do
    brew_install ${PACKAGES_NAME[$index]}
  done

  echo "Installing apps..."

  # brew cask
  brew_tap phinze/cask
  brew_install brew-cask
  brew_tap caskroom/versions

  local -a APPS_NAME=(
    "Google Chrome"
    "Firefox"
    "Dropbox"
    "Copy"
    "FileZilla"
    "ImageOptim"
    "iStat Menus"
    "KeePassX"
    "Mamp"
    "Sequel Pro"
    "Skype"
    "Spotify"
    "VMware Fusion"
    "VirtualBox"
    "VLC"
    "XtraFinder"
  )

  for index in ${!APPS_NAME[*]}; do
    app=$(echo ${APPS_NAME[$index]} | tr "A-Z" "a-z" | tr " " "-")
    cask_install "${APPS_NAME[$index]}" "$app"
  done

  # names that does not follow the same pattern
  cask_install "Sublime Text 3" "sublime-text"
  cask_install "Alfred 2" "alfred"
  cask_install "iTerm 2" "iterm2"
}